### ISSUE TITLE
Can't connect seed node

### ISSUE THREAD

**Issue by liray-unendlich** [Lonero-Team/Lonero-Beta#1]
Hi. I am hosting forknoted on my VPS, but I can't connect any seed node.

Here is my procedure of installation forknoted.
1. Host new server on Vultr: Ubuntu 16.04/2core/1GB RAM

2. enter these commands
```
git clone https://github.com/Lonero-Team/Lonero-Beta.git
cd Lonero-Beta
tar -xvzf forknoted
mv "forknoted (copy)" forknoted
./forknoted --config-file /root/Lonero-Beta/lonero.conf --seed-node 142.93.171.115:34414
```
I got these error:
![image](https://user-images.githubusercontent.com/15893314/46794788-90e2e980-cd83-11e8-8de8-8ea8e6c40b57.png)

Ofcourse i tried to host other VPS server. but all VPS can't connect seed node.

**Comment by Mentors4EDU** [comment]
Fixing in current update. Try to connect to port RPC port when binding. Also keep in mind, issues can come when mining on VPS servers. New seed notes about to be hosted + synced soon.
